CREATE TABLE IF NOT EXISTS usuario ( id BIGINT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, rol VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS socio ( id BIGINT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(255) NOT NULL, apellido VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, dni VARCHAR(50) UNIQUE NULL, fecha_alta DATE DEFAULT CURRENT_DATE, activo BOOLEAN DEFAULT TRUE );
CREATE TABLE IF NOT EXISTS actividad ( id BIGINT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(255) UNIQUE NOT NULL, activo BOOLEAN DEFAULT TRUE );
CREATE TABLE IF NOT EXISTS inscripcion ( id BIGINT AUTO_INCREMENT PRIMARY KEY, socio_id BIGINT, actividad_id BIGINT, fecha DATE DEFAULT CURRENT_DATE );
